name: Go

on:
  push:
    branches: [ Rewrite, master ]
  pull_request:
    branches: [ Rewrite, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build

    - name: Test
      run: go test -v ./...
